### ISSUE TITLE
Emoji list is black nd white on Chrome, missing emojis

### ISSUE THREAD

**Issue by RicS12** [joaoeudes7/V-Emoji-Picker#19]
From my side this is not working properly. Not even with font-face and adding the 2 external fonts you provided.

![image](https://user-images.githubusercontent.com/48968578/65362823-f0be5300-dbd6-11e9-92c6-a0c45339649f.png)

When I check the emojis.json and the emojis.js from where the packData comes from, I'm getting this:

![image](https://user-images.githubusercontent.com/48968578/65361777-d1bdc200-dbd2-11e9-8e77-3752480a2b2e.png)

![image](https://user-images.githubusercontent.com/48968578/65361750-ba7ed480-dbd2-11e9-8f17-f721e2a0d8ac.png)

There are missing emojis.

Browser is Chrome.
OS is windows 7 and 10.
If possible, please help so that I can get a full list with color and no missing emojis.

This is the latest version - 1.1.7

**Comment by joaoeudes7** [comment]
How did you apply external sources? It should have worked with the external source.

**Comment by RicS12** [comment]
Hi!

Thanks for answering and sorry for the delay. I'm adding:

```
<style lang="css" scoped>:
@font-face {
  font-family: Twemoji;
  font-weight: 400;
  font-display: swap;
  src: url(https://ucarecdn.com/73cba3b1-b2fa-45d9-89e3-886542974668/)
    format("truetype");
}

/* @font-face {
  font-family: NotomojiColor;
  font-weight: 400;
  font-display: swap;
  src: url(https://cdn.glitch.com/61908de1-dd0a-4359-a54b-6cb6d41bb5fd%2FNotoColorEmoji.ttf?1513108808150)
    format("truetype");
} */
</style>
```

And none of them work, I also tried to directly apply it: 

```
       <VEmojiPicker
        :pack="emojisNative"
        labelSearch="Search"
        @select="selectEmoji"
        style="font-family: NotomojiColor" on 
      />
```

Doesn't work :(

**Comment by RicS12** [comment]
I also went to https://codesandbox.io/s/vue-example-emoji-picker-jojl2 to test your project, and even though uncommenting the font-face makes the list coloured, they're still being printed black and white, and some of them still are white square (for example the first smiling face).

![image](https://user-images.githubusercontent.com/48968578/65567101-f5f70700-df22-11e9-92cf-e95ab2b301ed.png)

**Comment by joaoeudes7** [comment]
This is because the library emits the Unicode emoji and sends it to Input's v-model variable, so you need to define a style that contains the emoji font inside Input if you want it to show icons as shown in the library.

**Comment by RicS12** [comment]
Yeah, that worked in the sandbox. Thanks!

I have also verified that the issue with the emoji color might be because my windows 7 doesn't have the NotoColorEmoji.ttf installed in the OS, and when I try to install it by pasting the .ttf file in the Fonts folder from the Control Panel, I get an error that it is an unvalid file. 

I'll be working this on my end, but I believe it should be working normally for everyone else.
