### ISSUE TITLE
couldn't insert emoji between other words

### ISSUE THREAD

**Issue by UMRzcz-831** [joaoeudes7/V-Emoji-Picker#23]
thanks bro 🙃, appreciate your efforts coding this picker .
there's problems:
when i insert a emoji ，it would be added to the tail of the sentence，thats not quite convenient.
plus,the picker is not available to, choose emoji consistently

**Comment by joaoeudes7** [comment]
Thanks for the recommendations, which are in fact needing these improvements, I am adding on demand.

I just don't understand the part where it says "plus, the picker is not available to choose emoji consistently"

**Comment by UMRzcz-831** [comment]
hh.. sorry 4 my poor English🤣
i mean it's not very friendly to choose emojis continuously, like typing "🤣🤣🤣"  need 3 times of opening the emoji picker

**Comment by joaoeudes7** [comment]
No problem :rofl: 
This behavior only happens on the demo page, it is optional, there is a comment in the code :)

![image](https://user-images.githubusercontent.com/16367752/65560627-d1486280-df15-11e9-82f7-06066162cf94.png)
