### ISSUE TITLE
some problem i can't resolve

### ISSUE THREAD

**Issue by weitingGao** [joaoeudes7/V-Emoji-Picker#25]
I need your help
vue.runtime.esm.js:619 [Vue warn]: $attrs is readonly.

found in

---> <VEmojiPicker>
       <TextAndLink> at packages/operating/components/textAndLink/index.vue
         <ElTabPane> at packages/tabs/src/tab-pane.vue
           <ElTabs> at packages/tabs/src/tabs.vue
             <EditForm> at packages/operating/views/reply/follow.vue
               <Index> at packages/operating/views/reply/index.vue
                 <AppMain> at src/layout/components/AppMain.vue
                   <Layout> at src/layout/index.vue
                     <App> at src/App.vue
                       <Root>
warn @ vue.runtime.esm.js:619
(anonymous) @ vue.runtime.esm.js:3497
reactiveSetter @ vue.runtime.esm.js:1045
updateChildComponent @ vue.runtime.esm.js:4130
prepatch @ vue.runtime.esm.js:3125
patchVnode @ vue.runtime.esm.js:6302
updateChildren @ vue.runtime.esm.js:6187
patchVnode @ vue.runtime.esm.js:6313
updateChildren @ vue.runtime.esm.js:6187
patchVnode @ vue.runtime.esm.js:6313
updateChildren @ vue.runtime.esm.js:6187
patchVnode @ vue.runtime.esm.js:6313
patch @ vue.runtime.esm.js:6476
Vue._update @ vue.runtime.esm.js:3942
updateComponent @ vue.runtime.esm.js:4060
get @ vue.runtime.esm.js:4473
run @ vue.runtime.esm.js:4548
flushSchedulerQueue @ vue.runtime.esm.js:4304
(anonymous) @ vue.runtime.esm.js:1980
flushCallbacks @ vue.runtime.esm.js:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js:1933
nextTick @ vue.runtime.esm.js:1990
queueWatcher @ vue.runtime.esm.js:4396
update @ vue.runtime.esm.js:4538
notify @ vue.runtime.esm.js:730
reactiveSetter @ vue.runtime.esm.js:1055
proxySetter @ vue.runtime.esm.js:4625
update:inputText @ follow.vue?8121:37
invokeWithErrorHandling @ vue.runtime.esm.js:1854
invoker @ vue.runtime.esm.js:2179
invokeWithErrorHandling @ vue.runtime.esm.js:1854
Vue.$emit @ vue.runtime.esm.js:3882
set @ index.vue?cda0:83
selectEmoji @ index.vue?cda0:127
invokeWithErrorHandling @ vue.runtime.esm.js:1854
invoker @ vue.runtime.esm.js:2179
invokeWithErrorHandling @ vue.runtime.esm.js:1854
Vue.$emit @ vue.runtime.esm.js:3882
(anonymous) @ v-emoji-picker.umd.js:2137
step @ v-emoji-picker.umd.js:896
(anonymous) @ v-emoji-picker.umd.js:877
(anonymous) @ v-emoji-picker.umd.js:870
__awaiter @ v-emoji-picker.umd.js:866
fb15.VEmojiPicker.onSelectEmoji @ v-emoji-picker.umd.js:2134
invokeWithErrorHandling @ vue.runtime.esm.js:1854
invoker @ vue.runtime.esm.js:2179
invokeWithErrorHandling @ vue.runtime.esm.js:1854
Vue.$emit @ vue.runtime.esm.js:3882
(anonymous) @ v-emoji-picker.umd.js:1877
step @ v-emoji-picker.umd.js:896
(anonymous) @ v-emoji-picker.umd.js:877
(anonymous) @ v-emoji-picker.umd.js:870
__awaiter @ v-emoji-picker.umd.js:866
fb15.EmojiList.onSelect @ v-emoji-picker.umd.js:1875
click @ v-emoji-picker.umd.js:1755
invokeWithErrorHandling @ vue.runtime.esm.js:1854
invoker @ vue.runtime.esm.js:2179
original._wrapper @ vue.runtime.esm.js:6911
Show 28 more frames
vue.runtime.esm.js:619 [Vue warn]: $listeners is readonly.

found in

---> <VEmojiPicker>
       <TextAndLink> at packages/operating/components/textAndLink/index.vue
         <ElTabPane> at packages/tabs/src/tab-pane.vue
           <ElTabs> at packages/tabs/src/tabs.vue
             <EditForm> at packages/operating/views/reply/follow.vue
               <Index> at packages/operating/views/reply/index.vue
                 <AppMain> at src/layout/components/AppMain.vue
                   <Layout> at src/layout/index.vue
                     <App> at src/App.vue
                       <Root>

thanks

**Comment by joaoeudes7** [comment]
Hello, Thanks for reporting, but could you provide more information on how you are using the plugin? This log does not bring rich information.

**Comment by weitingGao** [comment]
I followed the example you provided, but the browser keeps reporting this error, which seems to be a vue version problem

**Comment by weitingGao** [comment]
I followed the example you provided, but the browser keeps reporting this error, which seems to be a vue version problem.
The error is
$attrs is readonly.
$listeners is readonly

**Comment by joaoeudes7** [comment]
In the example there is no errors like this, I will study the case again

**Comment by weitingGao** [comment]
OK,thanks.
If you have any progress, please let me know

**Comment by joaoeudes7** [comment]
Error in import plugin on doc, sorry! Try this:

```vue
<template>
  <div id="app">
    <VEmojiPicker :pack="emojisNatives" @select="selectEmoji" />
  </div>
</template>

<script>
import VEmojiPicker from 'v-emoji-picker';
import packEmoji from "v-emoji-picker/data/emojis.js";

export default {
  name: 'Demo',
  components: {
    VEmojiPicker
  },
  data: () => ({
    emojisNatives: packEmoji
  }),
  methods: {
    selectEmoji(emoji) {
      console.log(emoji)
    }
  }
}
</script>
```
