### ISSUE TITLE
Emoji's selection box not aligned

### ISSUE THREAD

**Issue by flaviocordova** [joaoeudes7/V-Emoji-Picker#26]
Trying to use it in a Vuetify app and selection box is aligned to Emoji, like this:

![image](https://user-images.githubusercontent.com/17955980/69753973-82949000-1133-11ea-9d0a-13048947a134.png)

Running on Chrome/MacOS

**Comment by joaoeudes7** [comment]
I will reach a state of a project with vuetify to solve the problem.
Thanks for reporting
