### ISSUE TITLE
Minor Documentation Fix

### ISSUE THREAD

**Issue by flaviocordova** [joaoeudes7/V-Emoji-Picker#27]
Since the emoji information inside emojis.json are in a data property, documentation (README) should be fixed in one of the two ways:

* Option 1
```
 <VEmojiPicker :pack="pack.data" @select="selectEmoji" />
```

* Option 2
```
  data: () => ({
    pack: packData.data
  }),
```

**Comment by joaoeudes7** [comment]
Thanks, fixed! Now using file '.js' (smaller)
