### ISSUE TITLE
Here is a issue about use font face

### ISSUE THREAD

**Issue by KimberlyZou** [joaoeudes7/V-Emoji-Picker#28]
I have download a font face(Notocoloremoji.ttf), I use it in emoji-picker, but it not work. And I use the link about the font face it can work. Could you please help me about this issue?

**Comment by joaoeudes7** [comment]
Have you tried importing from the local path as you do on the remote path?

**Comment by KimberlyZou** [comment]
Yes,I have tried. But it show me.
![Uploading image.png…]()

**Comment by KimberlyZou** [comment]
I get the reason.It seemed my browser version is too low. My Chrome version is 54.0, it couldn't work. But can be work on Chrome 68+. How to fix this or have any idea? I need to support Chrome 49+.
The error massage is
 `Failed to decode downloaded font: http:// localhost:8080/fonts/.....NotoColorEmoji.15549c9c.ttf`
`OTS parsing error： Not a valid font data`

**Comment by joaoeudes7** [comment]
[This](https://stackoverflow.com/questions/34288778/failed-to-decode-downloaded-font-ots-parsing-error-invalid-version-tag-rails) it can help

> I got the reason.It seemed my browser version is too low. My Chrome version is 54.0, it couldn't work. But can be work on Chrome 68+. How to fix this or have any idea? I need to support Chrome 49+.
> The error massage is
> `Failed to decode downloaded font: http:// localhost:8080/fonts/.....NotoColorEmoji.15549c9c.ttf`
> `OTS parsing error： Not a valid font data`

[This](https://stackoverflow.com/questions/34288778/failed-to-decode-downloaded-font-ots-parsing-error-invalid-version-tag-rails) it can help
