### ISSUE TITLE
Possibly Missing documentation v2.0.1

### ISSUE THREAD

**Issue by flaviocordova** [joaoeudes7/V-Emoji-Picker#31]
Version 2.0.1 (or 2.0.0, not sure which version exactly) have changed how to use v-emoji-picket but documentation is not updated.

1) There's no need to import emoji pack. Actually, the following line throws an error:

```
import packEmoji from "v-emoji-picker/data/emojis.js";
```

this is actually mentioned in some topics (migrating to v2) but should be considered in the example.

2) selected emoji was sent to event as event.emoji, now is event.data

**Comment by joaoeudes7** [comment]
Sorry, I forgot this part, I will be reviewing the documentation at this time, thanks

**Comment by joaoeudes7** [comment]
Be welcome to help whenever you want, thanks
