### ISSUE TITLE
vue-router.esm.js?8c4f:2079 TypeError: window.Vue.use is not a function

### ISSUE THREAD

**Issue by vanwhebin** [joaoeudes7/V-Emoji-Picker#34]
It seems not compatible with vuejs 2.6

**Screenshots**
![image](https://user-images.githubusercontent.com/8357785/71949352-25016200-320e-11ea-82e5-854244c7cf32.png)
![image](https://user-images.githubusercontent.com/8357785/71949496-b1ac2000-320e-11ea-95be-ec56107281c2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera & Firefox

**Additional context**
Vuejs: 2.6.10

**Comment by joaoeudes7** [comment]
The problem is not in version, I have already tested with version 2.5 and it works.
How are you importing? Globally or locally?

**Comment by vanwhebin** [comment]
> The problem is not in version, I have already tested with version 2.5 and it works.
> How are you importing? Globally or locally?

Thanks for your quick reply. 
I imported it in my custom component locally.
It works smoothly sometimes while sometimes not. 
for example, I refreshed the page several times then this issue vanished.

at present, i removed the emoji part, everything works well.

**Comment by joaoeudes7** [comment]
Did you use the plugin before the upgrade? I changed some props, in the readme shows the modifications, and you can see the usage example in this new version here: https://codesandbox.io/s/vue-example-emoji-picker-2-746pq

**Comment by vanwhebin** [comment]
Yes, i checked your example and used it in my project, however, error raised.
![image](https://user-images.githubusercontent.com/8357785/72121195-548ea680-3395-11ea-91f1-bec62d0f467c.png)

i changed the vuejs version in codepen example which runs as expected.
![image](https://user-images.githubusercontent.com/8357785/72121312-a20b1380-3395-11ea-97b3-3aadf4831c0c.png)

but in my project, it does not. :/
![image](https://user-images.githubusercontent.com/8357785/72121339-b94a0100-3395-11ea-931c-2c743476a4f2.png)

**Comment by joaoeudes7** [comment]
Try change version to 2.0.3 plz

**Comment by vanwhebin** [comment]
Thanks for your work!
