### ISSUE TITLE
Increase Emoji Size

### ISSUE THREAD

**Issue by Andrewsuares** [joaoeudes7/V-Emoji-Picker#37]
Hello,

Is it possible to increase the emoji size when viewing the emoji? Thanks.

**Comment by joaoeudes7** [comment]
Hello, at the moment this is not possible, but I will implement it soon. Thanks for the suggestion.
And if you want to implement, you will be welcome :)

**Comment by joaoeudes7** [comment]
Added in version 2.1.1! :laughing:

**Comment by Andrewsuares** [comment]
Thanks Joao! How do I use use the zoom?

**Comment by joaoeudes7** [comment]
I didn't add to Doc, the prop is: `@Prop({ default: 32 }) emojiSize!: number`

**Comment by Andrewsuares** [comment]
Hello, is it possible to increase the emoji size that are displayed after submitting and viewed? (not in the picker)

**Comment by joaoeudes7** [comment]
Yes, only set a variable and parse in prop emojiSize and change a variable to any value

**Comment by danieltttt** [comment]
how can I use my customer emojis?
