### ISSUE TITLE
[feature request] i18n

### ISSUE THREAD

**Issue by 1001v** [joaoeudes7/V-Emoji-Picker#38]
Hello. Please provide an ability to pass an object with translation to another language. I see that we can customize the search placeholder now, but i don't see how i can translate categories properly. Thank you.

**Comment by joaoeudes7** [comment]
Hello, Thank you for contributing request for features!  I intend to bring this in the next version!

**Comment by loginetsolutions** [comment]
There is no show/hide prop? Thanks
