### ISSUE TITLE
[feature request] typings for typescript

### ISSUE THREAD

**Issue by 1001v** [joaoeudes7/V-Emoji-Picker#39]
Hello. I see that the library is built with typescript, which is cool. However, there're no typings we could use with this library inside a typescript project. Please provide typings. Thank you.

**Comment by joaoeudes7** [comment]
Hello, thanks for your interest :) This plugin is compiled by vue-cli, but does not automatically generate typescript types, I need to check how to do this

**Comment by 1001v** [comment]
@joaoeudes7 i believe you could start with declaration option in the tsconfig https://www.typescriptlang.org/docs/handbook/compiler-options.html

**Comment by joaoeudes7** [comment]
@1001v If you know how to solve this problem quickly I would be very grateful to receive your pull request. :)
I am finishing some things and I will take care of that soon.

**Comment by 1001v** [comment]
Well, now i believe it's not that simple. I've ended up reading this thread https://github.com/vuejs/vue-cli/issues/1081 and it looks like there's no simple solution.

**Comment by joaoeudes7** [comment]
@1001v Exactly! See the last answer, I need to create settings for the rollup

**Comment by joaoeudes7** [comment]
Fixed in new version! Thanks :)
