### ISSUE TITLE
When I use it on my project the placeholder prop is not been use

### ISSUE THREAD

**Issue by MoisesFlores22** [joaoeudes7/V-Emoji-Picker#4]

**Comment by joaoeudes7** [comment]
I do not know if I understood correctly, but if you do not want to use the placeholder, set the labelSearch prop to empty

```vue
<template>
  <div id="app">
    <VEmojiPicker :pack="pack" labelSearch="" @select="selectEmoji" />
  </div>
</template>
```

**Comment by MoisesFlores22** [comment]
Already try that is not workin

**Comment by MoisesFlores22** [comment]
![image](https://user-images.githubusercontent.com/23325000/54054547-19897880-41b0-11e9-9f36-7cb1ff681e51.png)

**Comment by MoisesFlores22** [comment]
This issue should be still open

**Comment by joaoeudes7** [comment]
> Already try that is not workin

![image](https://user-images.githubusercontent.com/16367752/54060228-b06b2a80-41da-11e9-8566-b0535228a388.png)


Ohh yes! Sorry, I had made updates and forgot to update the component in npm, upgrade to the latest version :)
