### ISSUE TITLE
ReferenceError on page reload when using in Nuxt

### ISSUE THREAD

**Issue by frontwero** [joaoeudes7/V-Emoji-Picker#40]
**Describe the bug**
I use this component in a NuxtJs project (SSR). When I reload the page I get a ReferenceError: document is not defined (see screenshot). Also after trying to put the components between the 'client-only' tags.

**To Reproduce**
1. Create a NuxtJs SSR project
2. install this component
3. import the component in a page
4. reload the page in the browser

**Expected behavior**
No errors and work as supposed

**Screenshots**
![screencapture-192-168-1-77-3000-profile-wildtigress-2020-02-18-12_45_38](https://user-images.githubusercontent.com/45240453/74735667-73fcd700-5251-11ea-9cc4-5f1a49ba9855.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina v: 10.15.3
 - Browser Chrome
 - Version 80.0.3987.106 (Official Build) (64-bit)

**Comment by joaoeudes7** [comment]
Hi, thanks for reporting the problem.

I am passing the plugin to generate the bundle through rollup, and soon it will open doors for solutions to a problem like this.
I hope to release a version with this problem solved later this week

**Comment by joaoeudes7** [comment]
I tried everything to solve this problem directly from the plugin, unfortunately I would have to publish another version since I was unable to generate a rollup output with different settings for the vue-rollup.

I recommend that you try to run as a plugin client within Nuxt.

I await your feedback

**Comment by frontwero** [comment]
Hi João, for me, the solutions were to import it directly in the Vue components section in the SFC.
```
    components : {
      VEmojiPicker : () => import('v-emoji-picker'),
    },
```
Thanks for your effort.

**Comment by joaoeudes7** [comment]
Wow! Great news! Thanks for sharing! :)

**Comment by onhate** [comment]
This is how it works now

```
  components : {
      VEmojiPicker : () => import('v-emoji-picker').then(e => e.VEmojiPicker)
    },
```
