### ISSUE TITLE
Id issue

### ISSUE THREAD

**Issue by diadal** [joaoeudes7/V-Emoji-Picker#41]
please fix this warning 
`import{Prop as e,Component as n,Vue as o,Emit as t,Watch as a}from"vue-property-decorator";`
`var s=function`
<img width="482" alt="Screenshot 2020-02-19 at 09 16 16" src="https://user-images.githubusercontent.com/19895516/74815113-ea084900-52f8-11ea-8a77-cf2486fdac45.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOs
 - Browser [e.g. chrome, safari] safari, chrome

**Comment by joaoeudes7** [comment]
Thanks, Fixed in the latest version :)
