### ISSUE TITLE
Missing font in font-family

### ISSUE THREAD

**Issue by 1001v** [joaoeudes7/V-Emoji-Picker#42]
Hello. Please add 'EmojiOne Color' font in emoji font-family. This font is used in linux. Thank you.

**Comment by joaoeudes7** [comment]
Available in the latest version :) Give me feedback plz

**Comment by joaoeudes7** [comment]
Available in the latest version :) Give me feedback plz

**Comment by 1001v** [comment]
@joaoeudes7 looks good to me, thank you.
