### ISSUE TITLE
github pages, can't show emoji picker when button is clicked....

### ISSUE THREAD

**Issue by ramteen85** [joaoeudes7/V-Emoji-Picker#43]
So I added a Vue Project to github pages.

I had a feature in the project where you would click a button and it would show the emoji picker.
When I deployed the vue project to github, the emoji picker won't show up. but when doing npm run serve as a localhost it works fine. The html element VEmojiPicker shows up all in lowercase. But it shows up as an invisible element and no emoji picker in sight.

is there any step i missed?

i followed steps to upload to github pages as such.

https://www.youtube.com/watch?v=SKXkC4SqtRk

**Comment by joaoeudes7** [comment]
Do you have the link to the page you tested on?

**Comment by ramteen85** [comment]
this is a website i am experimenting with.
go to:

https://ramteen85.github.io/confessions_frontend/#/

To log in - use:
username: test1@test.com
password: 123

Now once you log in and the page is loaded, click the message dropdown on your navbar.
click a conversation and your inbox with messages between you and that user will load up.

Near your send message button, is the button for the emoji picker. Clicking that should trigger it.
Instead, youll see the element will show in the dev tools, but the actual emoji picker wont show.
it works fine in dev mode though.

**Comment by joaoeudes7** [comment]
Try to import like this:
`import { VEmojiPicker } from 'v-emoji-picker';`

**Comment by nkyokoo** [comment]
Can you show code?

**Comment by ramteen85** [comment]
> Try to import like this:
> `import VEmojiPicker from 'v-emoji-picker';`

works beautiful! thank you!
guess theres a bug in the global declaration when uploading to github.io
