### ISSUE TITLE
Get emoji data from emoji aliases / Save to DB

### ISSUE THREAD

**Issue by loginetsolutions** [joaoeudes7/V-Emoji-Picker#45]
Trying to:
1. display emoji.data in my input (get it from emoji.data) no problem
2. save the message to DB: replace in the message emoji.data by emoji.aliases and axios to save
3. retrieve the message from DB: replace in the message emoji.aliases with emoji.data and show the message in the chat container
Any help will be appreciated.

**My problem is how to get emoji.data from emoji.aliases and vice-versa**
How can I get the whole IEmoji array of objects if you remove the pack?

Otherwise, I have to change MySQL collation to save emoji.data which is not suitable in my case.

Thanks.

**Comment by guanzo** [comment]
I have the same request, expose the emoji array for library users. https://github.com/joaoeudes7/V-Emoji-Picker/issues/47

**Comment by joaoeudes7** [comment]
Thanks for the sugestion! Feature added in version 2.1.6 :smile: 
See the example in #47
