### ISSUE TITLE
Expose `emojisDefault` and `categoriesDefault` as named exports

### ISSUE THREAD

**Issue by guanzo** [joaoeudes7/V-Emoji-Picker#47]
Could you export these files, so I could import them like 

```js
import VEmojiPicker, { emojisDefault, categoriesDefault } from 'v-emoji-picker'
```

Thanks

**Comment by joaoeudes7** [comment]
Thanks for the sugestion! Feature added in version 2.1.6 :smile: 
https://codesandbox.io/s/vue-example-emoji-picker-2-746pq

**Comment by guanzo** [comment]
@joaoeudes7 Thanks for acting on my issues so quickly.
