### ISSUE TITLE
"Frequently" used emojis do not persist between page refresh.

### ISSUE THREAD

**Issue by guanzo** [joaoeudes7/V-Emoji-Picker#48]
**Describe the bug**
"Frequently" used emojis only seem to be stored in memory. On page refresh, they are gone.

**To Reproduce**
1. Pick emoji.
2. Go to frequently used tab, emoji appears,
3. Refresh page, go to frequently used tab, it's empty.

**Expected behavior**
Frequently used emojis should persist to disk, like localStorage. It's kind of useless without persistence.

**Comment by joaoeudes7** [comment]
Thanks for the sugestion! Feature added in version 2.1.6 :smile:
