### ISSUE TITLE
Make `customEmojis` reactive

### ISSUE THREAD

**Issue by guanzo** [joaoeudes7/V-Emoji-Picker#54]
**Is your feature request related to a problem? Please describe.**
I want to be able to add emojis dynamically to an existing `<VEmojiPicker>`. However, the lib only checks for `customEmojis` in `created()`, then never again.

**Describe the solution you'd like**
React to changes to the  `customEmojis` prop, and have the component display the new emojis.

**Describe alternatives you've considered**
1. Reaching into the component and mutating the data myself :/
2. Destroying and recreating component with new `customEmojis`, when my app finishes fetching the custom emoji data.

I noticed that `customCategories` is already reactive, since it's being used in the `categoriesFiltered` computed property, which is great. 👍

Thanks

**Comment by joaoeudes7** [comment]
Good! I will solve this, thank you!

**Comment by guanzo** [comment]
Sorry to keep pinging you with issues, but I noticed that your localStorage logic (for persisting "Frequently" used emojis), relies on array indexes. If my `customEmojis` is dynamic, then relying on indexes to restore emojis is obviously not going to work.

**Comment by joaoeudes7** [comment]
Yes, I noticed that too, I am trying to solve this problem and I will soon be launching a good update: D

**Comment by guanzo** [comment]
Hey.. another issue 😩 . These stupid browsers: Brave & Safari, throw errors when localStorage is accessed in a nested, 3rd party iframe. 

I wrote a localStorage wrapper for myself,  which works for my use case. https://gist.github.com/guanzo/571a0026ba90454fa9a6fde77f7701b6

But your lib also uses localStorage, and my error reporting service is going crazy.

![](https://i.gyazo.com/66c4713bf589daee31b5cd62af0c7472.png)

I'm wondering if you could somehow allow users of this component to override usage of `window.localStorage`, with a custom storage API. To make it easy for everyone, you could mandate that this custom storage API implement this standard interface, https://developer.mozilla.org/en-US/docs/Web/API/Storage.

Thanks, still loving this library :D

**Comment by guanzo** [comment]
Another easier solution to my above problem, is have `this.mapperEmojisCategory` check if `customEmojis` contains emojis with a `Frequently` category. If so, use **only** those emojis for the `Frequently` category.

**Comment by joaoeudes7** [comment]
Hi, sorry for the delay, I had already implemented a solution, available in version 2.1.8, had forgotten to publish, thanks :)

**Comment by joaoeudes7** [comment]
@guanzo Did you resolve your update issue?

**Comment by guanzo** [comment]
`customEmojis` is now reactive, so that solves my original issue, ty.

The issues i'm facing now are:

1. You're still saving emoji indexes in localStorage, to restore "Frequently" emojis. What happens if `customEmojis` changes at runtime? These indexes becomes useless, b/c they now refer to the wrong emoji, threfore the "Frequently" feature is useless.
2. Accessing localStorage in 3rd party iframe in Brave & Safari, throws an error. My sentry is blowing up with 150k+ errors, I need to handle this, preferably by not ignoring the error.

I'm also beginning to need more features, such as scoped slots, pagination events, virtual scrolling, etc. I'm loading in thousands of new emojis at runtime, for each individual user. I need better performance, UI and network wise, b/c loading thousands of images into the DOM is not ideal. 

These features may be out of scope for this lib, and my use case of running in a Twitch.tv extension is unusual, so rather than continue to bother you, I've forked the repo.

**Comment by joaoeudes7** [comment]
1. Yes, saving the emoji index from the root emojis is a mistake, we really need to fix it.
2. I will check this problem on brave, but here (firefox, chrome) it doesn't happen.

- Scopes will be necessary, I am providing this at the moment
- Events on the Scroll? How much do you think is necessary?
- I imagine that the "loading" property will not work in this case since we are dealing with Unicode icons and not images, which also does not avoid creating elements in the DOM, so Virtual Scroll is really necessary, you cannot replace it with "lazy"

Feel free to contribute, I will be happy to receive your contributions :)

**Comment by guanzo** [comment]
No errors on chrome and FF, just stupid Brave & Safari. So annoying.

* regarding scopes, 👍 
* to be honest i'm not sure if the lib should handle pagination or not, but it's something I need.
* I forgot to mention, i'm replacing all the default emojis, with [tweomjis](https://github.com/twitter/twemoji). And i'm loading in [BTTV Emotes](https://betterttv.com/emotes/top). These are all images, not unicode characters. As I said, my use case is rather unusual 😁 

I totally forgot about PR's, and jumped straight to forking haha. Will definitely contribute if I can. I'll have to learn typescript. From browsing your source, ts looks really elegant and easy to use!
