### ISSUE TITLE
[Vue warn]: $attrs is readonly. +[Vue warn]: $listeners is readonly.

### ISSUE THREAD

**Issue by vwmoose** [joaoeudes7/V-Emoji-Picker#55]
I've recently included _v-emoji-picker_ into my laravel project, Vue installed and working.

I imported it locally in my component as per the documentation (see below).
```
<script>
  import VEmojiPicker from 'v-emoji-picker';

  export default {
    components: { 
      VEmojiPicker,
    },
```
```
<VEmojiPicker 
     v-if="showEmojiPicker"
     @select="selectEmoji"
     class="emoji-picker" />
```
When I click on an emoji `selectEmoji()` is triggered and the emoji added to my `<input>`.  It is at this point the following two warnings appear in the console.
```
[Vue warn]: $attrs is readonly.
found in
---> <VEmojiPicker>
```
and 
```
[Vue warn]: $listeners is readonly.
found in
---> <VEmojiPicker>
```
Issue #25 appears to have had the same problem in the past and your suggestion fixed it, it appears I'm doing exactly as you suggested in this issue.

After some research on google it appears that this can be attributed to Vue being loaded multiple times?  Looking at your plugin it looks like it loads Vue as well, could this be the issue?

Thanks very much for a great plugin, looking forward to your help to rectify my problem. 

Cheers!

**Comment by vwmoose** [comment]
Just for further information, I removed the `v-if` from the component attributes so that _v-emoji-picker_ is loaded immediately and the same error occurs without any interaction with the component.

**Comment by joaoeudes7** [comment]
Hello, thanks for reporting, I will analyze the error and soon I will bring a solution

**Comment by Art3miX** [comment]
Hello,

Any fix to this issue? I just installed the pack and used the example, I see one $attr error and 2 @listener errors.

**Comment by joaoeudes7** [comment]
@Art3miX the property in `if` is mutable??

**Comment by Art3miX** [comment]
> @Art3miX the property in `if` is mutable??

I don't see the error now, I updated versions not long ago, not sure if this package was one of them.

But the `if` property was in my data object:
```
data() {
    return {
        showEmojis:  false, 
    }
}
```

**Comment by joaoeudes7** [comment]
@Art3miX Ok, it was just to confirm, thanks :)
