### ISSUE TITLE
Responsive Popup

### ISSUE THREAD

**Issue by Andrewsuares** [joaoeudes7/V-Emoji-Picker#59]
Hello,

The popup is a problem on a phone. Any way to make this better? Thanks.

![Screenshot_20200424_223611_com hobotraveler community](https://user-images.githubusercontent.com/35380745/80238643-67936100-867c-11ea-8f68-67d74d95c420.jpg)

**Comment by joaoeudes7** [comment]
It is just a container with emojis just to allow developers to customize as they like, that means it depends on each implementation in each project.

Mobile users generally have a keyboard where emojis are used, it is usual to use such via this plugin.
Useful when used in Desktops versions.

However, as stated before, the developer is free to implement a dialog or space to allocate how and where to show the plugin for a given type of screen.
