### ISSUE TITLE
Picker not displaying on 2.3.1

### ISSUE THREAD

**Issue by evanwirt** [joaoeudes7/V-Emoji-Picker#73]
**Describe the bug**
The picker isn't showing on 2.3.1 and am getting the error in the console:
  Failed to mount component: template or render function not defined
It shows fine on 2.3.0
2.3.1 has been released on npm.

**To Reproduce**
1. Go to: https://codesandbox.io/s/vue-example-emoji-picker-2-746pq?file=/package.json
2. Switch emoji-picker library to 2.3.1.
3. Click on emoji button.
4. Don't see emoji picker. See console error message.
5. Switch library to 2.3.0
6. Click on emoji button.
7. See picker appear.

**Expected behavior**
Picker shows up.

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]
 - Version [86.0.4240.75]

**Comment by joaoeudes7** [comment]
Sorry @evanwirt, @vmurgic, have changes in import module to support to global use.
To import local use:
```ts
import { VEmojiPicker, emojisDefault, categoriesDefault } from "v-emoji-picker";
```
To import global use:
```ts
import VEmojiPicker from "v-emoji-picker";

Vue.use(VEmojiPicker)
```
