### ISSUE TITLE
安装的2.3.1 版本组件不能加载

### ISSUE THREAD

**Issue by meiqinLiu** [joaoeudes7/V-Emoji-Picker#74]
**Describe the bug**
安装V-Emoji-Picker的当前最近版本2.3.1，引用的时候组件加载失败，提示错误“template or render function not defined”，
我回退到上一个版本2.3.0，又能使用了

vue的版本：
"vue": "^2.6.11",
 "vue-class-component": "^7.2.3",

**Comment by joaoeudes7** [comment]
Duplicate of #73
