### ISSUE TITLE
2.3.1 only working in dev, not in production

### ISSUE THREAD

**Issue by quantumwebco** [joaoeudes7/V-Emoji-Picker#78]
V-Emoji-Picker version 2.3.1 ```Vue.use(VEmojiPicker);```

When running npm run dev or watch, the emoji picker works fine
When running npm run prod the emoji picker does not show at all and no errors in the console

This happens in my local environment and on the live server and on other machines

Reverting back to 2.3.0 and ```Vue.component("VEmojiPicker", VEmojiPicker);``` seems to work

**Desktop (please complete the following information):**
 - OS: Windows/Linux
 - Browser Chrome
 - Version Latest

**Comment by joaoeudes7** [comment]
I will check and soon bring a solution

**Comment by joaoeudes7** [comment]
Fixed, thanks @quantumwebco  :)
