### ISSUE TITLE
How Insert consecutive emojis at the cursor position? 

### ISSUE THREAD

**Issue by thuongnd5499** [joaoeudes7/V-Emoji-Picker#94]
when I use @input of textarea, I only can insert 1 emoji at the cursor position, then next ones are inserted at the first position like this:
![image](https://user-images.githubusercontent.com/84675577/119267429-be20f500-bc18-11eb-9068-0b32e5bf81a7.png)

**Comment by joaoeudes7** [comment]
Hi, this plugin not intend to treat this, because the aim is to be as dynamic as possible. But you can get the position of cursor and split the string to put the emoji in between both parts of string 😄
